[build]
publish = "dist/crud-in-angular"
command = "ng build"

[dev]
  command = "json-server --watch db.json"
  publish = "dist/crud-in-angular"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[functions]]
  directory = "functions"
  command = "npm run start"
  runtime = "nodejs16.x"
